package com.example.ferrepaccha.ui.admin

enum class TipoSubpantalla {
    LOGIN,
    DASHBOARD,
    GESTION_GERENTE,
    GESTION_EMPLEADOS,
    FORMULARIO_USUARIO,
    GESTION_PRODUCTOS,
    DETALLE_PEDIDO,
    FORMULARIO_PRODUCTO,
    GESTION_PEDIDOS,
    BUSCAR_PEDIDOS,
    VER_CATALOGO
}
